wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1680700212.230955
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 13
      - 23
      4: 3.8.10
      5: 0.14.0
      8:
      - 5
