#define ぬ long long
#define お namespace
#define あ continue
#define へ multimap
#define ん multiset
#define ろ double
#define ぬよ return
#define り second
#define う string
#define つ switch
#define ら vector
#define す break
#define よ const
#define しやなろ first
#define つふ float
#define こ using
#define せ while
#define うつふ auto
#define おそと bool
#define に case
#define おく char
#define けり cout
#define おそ else
#define かわ endl
#define き pair
#define し void
#define かわちけなり <<=
#define い >>=
#define ねわ cin
#define ね for
#define ふ int
#define る map
#define ほ set
#define く std
#define たお !=
#define と %=
#define まへ &&
#define は &=
#define なろ *=
#define えめ ++
#define け +=
#define すつふ --
#define かわち -=
#define ま ->
#define んねわ /=
#define かわちけ ::
#define や <<
#define そ <=
#define れ >=
#define た >>
#define せほ if
#define さ |=
#define む ||
#define わ !
#define ぬよひ %
#define みそ &
#define み (
#define を )
#define そむ *
#define え +
#define もせ ,
#define やなろ -
#define ませ .
#define も /
#define なあ :
#define て ;
#define ひ <
#define よせ =
#define ゆ >
#define の ?
#define め [
#define ち ]
#define か {
#define な |
#define なり }
#include <bits/stdc++.h>
こ お く て ふ solve み を か う str_a もせ str_b て ねわ た str_a た str_b て ふ l よせ str_a ませ length み を て ね み ふ i よせ 0 て i ひ l て えめ i を か せほ み str_a め i ち れ 'a' を str_a め i ち かわち 32 て せほ み str_b め i ち れ 'a' を str_b め i ち かわち 32 て なり せほ み str_a ゆ str_b を ぬよ 1 て せほ み str_a ひ str_b を ぬよ やなろ 1 て ぬよ 0 て なり ふ main み を か ios_base かわちけ sync_with_stdio み false を て ねわ ませ tie み 0 を て けり や solve み を や '\n' て ぬよ 0 て なり 